frase = '  Curso em video  '
print(frase[3])
print(len(frase))
print(frase.count('1:'))
print(frase.find('e'))
print(frase.replace('Curso', 'Python'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.split())
print(frase.join('__'))